on:
  schedule:
  - cron: '26 4 * * 4'
  push:
    branches:
    - main
    tags:
    - 'v*'

env:
  REGISTRY: europe-docker.pkg.dev

jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'
    - uses: 'google-github-actions/auth@v2'
      with:
        project_id: 'mnacharov-eu-docker'
        workload_identity_provider: 'projects/152460024713/locations/global/workloadIdentityPools/github-com/providers/mnacharov-eu'
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: europe-docker.pkg.dev/mnacharov-eu-docker/push-to-gcp/main
        flavor: |
          latest=false
        tags: |
          type=semver,pattern={{version}}
          type=sha,enable=${{ github.ref == format('refs/heads/{0}', 'main') && github.event.schedule == null }}
          type=raw,enable=${{ github.event.schedule != null }},value={{date 'cron-YY-MM-DD'}}
    - name: Configure GC docker
      run: |
        gcloud auth configure-docker europe-docker.pkg.dev
    - name: Build & Push Airflow
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
